#!/bin/sh
logger -t S81Snort3 "Starting Snort3 IDS/IPS $0"
# set environment PATH to system binaries
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:$PATH
export TZ=$(cat /etc/TZ)
ENABLED=yes
PROCS=snort
ARGS="-z 1 --daq afpacket --daq-dir /opt/lib/daq --daq-var buffer_size_mb=32 --daq-var debug --daq-var fanout_type=hash --daq-var fanout_flag=defrag -Q -i eth0:br0 -c /opt/etc/snort/snort.lua -l /opt/var/log/snort -s 1518 -k none"
PREARGS=""
DESC=$PROCS
PRECMD="killall snort && echo 1 > /proc/sys/vm/compact_memory && ethtool -K eth0 gro off && ethtool -K br0 gro off"
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func
